drop TABLE if EXISTS Article;
drop TABLE IF EXISTS ListItem;


-- Article definition

CREATE TABLE "Article" (
	"MadiCustNo" INTEGER NOT NULL, 
	"CompNo" INTEGER NOT NULL, 
	"ItemNo" INTEGER NOT NULL, 
	"ItemName" VARCHAR(50), 
	"DeptNo" INTEGER, 
	"Text1" VARCHAR(50), 
	"Text2" VARCHAR(50), 
	"TextKeyb" VARCHAR(25), 
	"MatchCode" VARCHAR(50), 
	"SellingQuantityUni" INTEGER, 
	"PackQuantityUnit" INTEGER, 
	"StockQuantityUnit" INTEGER, 
	"TaraValue" FLOAT, 
	"AccountNo" FLOAT, 
	"WasteFactor" FLOAT, 
	"WarningTextNo" INTEGER, 
	"Tandem" FLOAT, 
	"StockItemNo" FLOAT, 
	"GroupItemNo" FLOAT, 
	"Totalizer" INTEGER, 
	"Locked" INTEGER, 
	"OpenArticle" INTEGER, 
	"TakeAway" INTEGER, 
	"PriceNegative" INTEGER, 
	"MultiplProhibited" INTEGER, 
	"MultiplForced" INTEGER, 
	"Discountable" INTEGER, 
	"Attendance" INTEGER, 
	"SpiritTax" INTEGER, 
	"BeverageTax" INTEGER, 
	"Scale" INTEGER, 
	"Deposit" INTEGER, 
	"ContentOverride" INTEGER, 
	"GuestGift" INTEGER, 
	"PrintWaiterDate" INTEGER, 
	"PrintOnZero" INTEGER, 
	"GuestCounter" INTEGER, 
	"CreditSale" INTEGER, 
	"PluNotFound" INTEGER, 
	"TimePeriodStat" INTEGER, 
	"OperatorStat" INTEGER, 
	"ImmediatePrint" INTEGER, 
	"IsSalesItem" INTEGER, 
	"IsStockItem" INTEGER, 
	"IsMagazineItem" INTEGER, 
	"AutoForSell" INTEGER, 
	"LevelForOrder" INTEGER, 
	"VoucherPrint" INTEGER, 
	"BlockedFromDay" VARCHAR(8), 
	"BlockedFromTime" VARCHAR(8), 
	"BlockedToDay" VARCHAR(8), 
	"BlockedToTime" VARCHAR(8), 
	"OrderTypeNo" INTEGER, 
	"SupplierNo" INTEGER, 
	"PrintTypeNo1" INTEGER, 
	"DispTypeNo" INTEGER, 
	"StockTypeNo" INTEGER, 
	"TextGroupNo" INTEGER, 
	"SelTextAcc" INTEGER, 
	"ArticleGrpNo" INTEGER, 
	"PriceGrpNo" INTEGER, 
	"ArtSelectNo1" INTEGER, 
	"ArtSelectNo2" INTEGER, 
	"ArtSelectNo3" INTEGER, 
	"ArtSelectNo4" INTEGER, 
	"BuffeNo" INTEGER, 
	"RecipeNo" INTEGER, 
	"MenuNo" INTEGER, 
	"PrintLabelNo" INTEGER, 
	"LabelAcc" INTEGER, 
	"ServiceCharge" INTEGER, 
	"HandStock" INTEGER, 
	"GuaranteeGrp" INTEGER, 
	"PrintKey" INTEGER, 
	"ProfitCalcBase" FLOAT, 
	"ProdTypeNo" INTEGER, 
	"ProdLocationNo" INTEGER, 
	"ProdQuant" INTEGER, 
	"Preparation" INTEGER, 
	"TextColorNo" INTEGER, 
	"VatNo" INTEGER, 
	"TakeAwayVatNo" INTEGER, 
	"WarningGroupNo" INTEGER, 
	"ShouldNotBeCounted" INTEGER, 
	"SelectGroupNo" INTEGER, 
	"ObjBrGrpNo" INTEGER, 
	"InfoAddress" VARCHAR(50), 
	"TableStatus" INTEGER, 
	"CompareContents" FLOAT, 
	"CompareUnitNo" INTEGER, 
	"CaptureSerialNo" INTEGER, 
	"CaptureSize" INTEGER, 
	"ExtLoyPoints" INTEGER, 
	"LastChanged" VARCHAR(8), 
	"Category1" INTEGER, 
	"Category2" INTEGER, 
	"Category3" INTEGER, 
	"IsWarranty" INTEGER, 
	"LoRange" FLOAT, 
	"HiRange" FLOAT, 
	"Years" INTEGER, 
	"CreationDate" VARCHAR(8), 
	"Seasonal" INTEGER, 
	"ReadyToBeDeleted" INTEGER, 
	"NoLoyaltyPoints" INTEGER, 
	PRIMARY KEY ("MadiCustNo", "CompNo", "ItemNo"), 
	FOREIGN KEY("ItemNo") REFERENCES "ListItem" ("ItemNo")
);

-- ListItem definition

CREATE TABLE "ListItem" (
	"MadiCustNo" INTEGER NOT NULL, 
	"CompNo" INTEGER NOT NULL, 
	"ItemNo" INTEGER NOT NULL, 
	"PriceListNo" INTEGER NOT NULL, 
	"Price" FLOAT, 
	"SpecPrice1" FLOAT, 
	"SpecPrice2" FLOAT, 
	"SpecPrice3" FLOAT, 
	"SpecPrice4" FLOAT, 
	"SpecPrice5" FLOAT, 
	"Locked" INTEGER, 
	"CalcSalesPrice" INTEGER, 
	"ExpGrMarginPerc" FLOAT, 
	"RecipeNo" INTEGER, 
	"StockTypeNo" INTEGER, 
	PRIMARY KEY ("MadiCustNo", "CompNo", "ItemNo", "PriceListNo"), 
	FOREIGN KEY("CompNo") REFERENCES "Article" ("CompNo"), 
	FOREIGN KEY("ItemNo") REFERENCES "Article" ("ItemNo"), 
	FOREIGN KEY("MadiCustNo") REFERENCES "Article" ("MadiCustNo")
);